arcoiris=("Azul", "Verde", "Rojo", "Amarillo")
print(arcoiris)
print("-longitud arcoiris--")
print(len(arcoiris))
animales=("pantera", "edad",20,"estatura",1.68,)
print(animales)
print("elementos de la tupla")
print(animales[2])
rateros=("uziel", "francisco", "franciscootravez")
y = list(rateros)
y[0]="ooo"
x=tuple(y)
print(x)
print("agregando elementos")
nanimal=("boby", "chetos")
y =list(nanimal)
print(y)
y .append("tontolin")
otratupla= tuple(y)
print(otratupla)
print("uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)